name: Deploy Autocrafts to Custom Domain (riteshraj.tech)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "src/data/**" 
  # schedule:
  #   - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 0. Calculate 90day date range
      - name: Calculate Date Range
        id: dates
        run: |
          echo "FROM_DATE=$(date -u -d '90 days ago' +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "TO_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      # 1. Fetch GitHub data 
      - name: Fetch GitHub Payload
        uses: riteshraj-shetage/octofetch@v1.0.0
        with:
          github_token: ${{ secrets.GH_PAT }}
          query_file: .github/octofetch/autocrafts.query.graphql
          variables: '{
                        "owner": "${{ github.repository_owner }}", 
                        "from": "${{ steps.dates.outputs.FROM_DATE }}", 
                        "to": "${{ steps.dates.outputs.TO_DATE }}" 
                      }'
          output_file: src/data/sourced.json

      # 2. Commit and Push payload back to this repo
      - name: Commit Payload back to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/data/sourced.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: automated payload sync [skip ci]"
            git push origin main
          else
            echo "Payload hasn't changed. Skipping commit."
          fi

      # 3. Set up the Bun environment
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # 4. Clean install UI dependencies 
      - name: Install Dependencies
        run: bun install --frozen-lockfile
        working-directory: .

      # 5. Compile the React UI 
      - name: Build Application
        run: bun run build
        working-directory: .

      # 6. Deploy natively to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: riteshraj.tech