name: Test Workflow

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Native Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Output
        run: cat ui/public/gh-data.json